name: 🐛 Bug report
description: Something not behaving as expected?
title: '[Bug]: '
labels: ['bug']
body:
- type: markdown
  attributes:
    value: |
      Please check for an existing issue and the [README](https://github.com/martincostello/dotnet-minimal-api-integration-testing/blob/main/README.md) before submitting a bug report.
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behaviour
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Actual behaviour
    description: What actually happens.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      Provide a link to a [minimalistic project which reproduces this issue (repro)](https://stackoverflow.com/help/mcve) hosted in a **public** GitHub repository.
      Code snippets, such as a failing unit test or small console app, which demonstrate the issue wrapped in a [fenced code block](https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) are also acceptable.

      This issue will be closed if:
      - The behaviour you're reporting cannot be easily reproduced.
      - The issue is a duplicate of an existing issue.
      - The behaviour you're reporting is by design.
  validations:
    required: false
- type: textarea
  attributes:
    label: Exception(s) (if any)
    description: Include any exception(s) and/or stack trace(s) you get when facing this issue.
    render: text
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering is useful.

      💡Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
