<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1861</NoWarn>
    <OutputType>Exe</OutputType>
    <RootNamespace>TodoApp</RootNamespace>
    <TargetFramework>net11.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="GitHubActionsTestLogger" Version="3.0.5" />
    <PackageReference Include="JustEat.HttpClientInterception" Version="5.1.4" />
    <PackageReference Include="MartinCostello.Logging.XUnit.v3" Version="0.7.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Microsoft.Playwright" Version="1.63.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.12.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.1" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="oauth-http-bundle.json;xunit.runner.json;xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="localhost-dev.pfx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TodoApp\TodoApp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Shouldly" />
    <Using Include="Xunit" />
  </ItemGroup>
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverageFormat>cobertura</CoverageFormat>
    <CoverageOutput>$([System.IO.Path]::Combine($(MSBuildThisFileDirectory), '..', '..', 'artifacts', 'coverage', '$(MSBuildProjectName)', 'coverage.xml'))</CoverageOutput>
    <CoverageRunSettings>$(MSBuildThisFileDirectory)tests.runsettings</CoverageRunSettings>
  </PropertyGroup>
  <Target Name="_AddCoverageArguments" BeforeTargets="_MTPAddArguments;InvokeTestingPlatform" Condition=" '$(CollectCoverage)' == 'true' ">
    <PropertyGroup>
      <_CoverageArguments>--coverage</_CoverageArguments>
      <_CoverageArguments>$(_CoverageArguments) --coverage-output-format %22$(CoverageFormat)%22</_CoverageArguments>
      <_CoverageArguments>$(_CoverageArguments) --coverage-output %22$(CoverageOutput)%22</_CoverageArguments>
      <_CoverageArguments>$(_CoverageArguments) --coverage-settings %22$(CoverageRunSettings)%22</_CoverageArguments>
    </PropertyGroup>
    <CreateProperty Value="$(TestingPlatformCommandLineArguments) $(_CoverageArguments)">
      <Output TaskParameter="Value" PropertyName="TestingPlatformCommandLineArguments" />
    </CreateProperty>
  </Target>
</Project>
