name: code-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  schedule:
    - cron: '0 6 * * 1'

permissions:
  actions: read
  contents: read

jobs:
  code-ql:

    runs-on: ubuntu-latest

    permissions:
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp', 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        build-mode: none
        languages: ${{ matrix.language }}
        queries: security-and-quality

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: '/language:${{ matrix.language }}'
